name: Build and deploy Node.js app to Azure Web App - muduo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build --if-present

      - name: Run tests
        run: npm run test --if-present

      - name: Zip the built app
        run: zip -r release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip the artifact
        run: unzip release.zip

      - name: Build Docker image
        run: docker build -t my-node-app .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push my-node-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'muduo'
          slot-name: 'Production'
          images: 'my-node-app:latest'

      - name: Login to Azure CLI
        run: az login --use-device-code
